server:
  port: 8762
spring:
  application:
    name: wp-persistence-server
  datasource:
      url: jdbc:mysql://127.0.0.1/o2o?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=false
      username: root
      password: 123456
  rabbitmq:
    addresses: 127.0.0.1
    port: 5672
    username: awp
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 1000
        max-idle: 100
        min-idle: 1
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://127.0.0.1:8888/eureka/

# mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: false
    auto-mapping-behavior: full